#!/bin/bash

source ./lp-config.sh
source "$outputDir/build.number"
version=$version-$build

butler push "$latestBuildsDir/$packageName-${version}_win32.zip" guard13007/scp-clicker:win32
butler push "$latestBuildsDir/$packageName-${version}_win64.zip" guard13007/scp-clicker:win64
butler push "$latestBuildsDir/$packageName-${version}_osx.zip" guard13007/scp-clicker:osx
butler push "$latestBuildsDir/$packageName-${version}_linux.zip" guard13007/scp-clicker:linux

echo "Waiting for 30 seconds and then checking status."

sleep 30
butler status guard13007/scp-clicker
