#!/bin/bash

if [ ! -e ./src/version.lua ]; then
  git submodule init
  git submodule update
  cd src/lib/pop
  git submodule init
  git submodule update
  cd ../../..
fi

moonc ./src
source version.sh
echo "version=\"$version-dev\"" > ./src/version.lua

love src
