return {
  [7]: {
    [[SCP-132 takes the form of a series of ███ glass tetrahedrons, each with a side length of 10.3 centimeters. Each instance of SCP-132 appears to contain a patch of desert sand. Occasionally scorpions and other desert creatures enter the confines of an instance of SCP-132 as if it were a continuous piece of desert. Creatures within SCP-132 have shown no awareness of the existence of anything outside of the object and attempts to influence the area within SCP-132 have failed.
    .
    Review of observed animal life within SCP-132 has proven inconsistent. Clusters of contiguous instances have been internally consistent and have been confirmed to display areas of every major desert. No method of pinpointing exact locations has been discovered; staff observing SCP-132 are advised to be on the lookout for any defining features that could aid in this endeavor.]]
  }
  [13]: {
    [[SCP-049 is humanoid in appearance, standing at 1.9 m tall and weighing 95.3 kg; however, the Foundation is currently incapable of studying its face and body more fully, as it is covered in what appears to be the garb of the traditional “Plague Doctor” from 15-16th century Europe. This material is actually a part of SCP-049’s body, as microscopic and genetic testing show it to be similar in structure to muscle, although it feels much like rough leather, and the mask much like ceramic. It was originally discovered in ██████, England, by local police. Mobile task force [REDACTED] responded to a suspected outbreak of [DATA EXPUNGED]. All civilians within a .5km radius were given class A amnestics as part of the initial containment procedure.
    .
    SCP-049 does not usually speak (See addendum A-1), although it seems to understand English perfectly well, and is completely docile until it tries to perform surgery. SCP-049’s touch is invariably lethal to humans. After contact with SCP-049’s hand(s), the victim (hereafter referred to as SCP-049-2) suffers [DATA EXPUNGED] and dies within moments. SCP-049 will then attempt to kill all humans it can see in a similar manner, supposedly to avoid interruption, before returning to SCP-049-2. It produces a bag made of [DATA EXPUNGED] containing scalpels, needle, thread, and several vials of an as-yet-unidentified substance, from somewhere within its body (research has been unable to locate these tools when inside of SCP-049 through X-ray and similar techniques) and begins dissecting SCP-049-2, as well as inserting various chemicals into the body. After approximately 20 minutes, SCP-049 will sew SCP-049-2 back up and become docile once more.
    .
    After a period of a few minutes, SCP-049-2 will resume vital signs and appears to reanimate. However, SCP-049-2 seems completely without higher brain functions, and will wander aimlessly until it encounters another living human. At that point, SCP-049-2's adrenaline and endorphin levels increase to approximately three-hundred (300) percent as it attempts to kill and ██████ any human beings it can find, before returning to its mindless state and wandering until it comes across more humans. At this stage, termination with extreme prejudice is allowed. Failure to enforce this protocol outside of testing scenarios (see addendum T-049-12) is punishable by termination.
    .
    Detailed autopsies of SCP-049-2 have found several unusual substances (along with usual substances in large amounts) within the bodies, including [DATA EXPUNGED]. However, several have yet to be identified.]]
  }
  [14]: {
    [[SCP-1471 is a free 9.8MB application for mobile devices named "MalO ver1.0.0" in online application stores. SCP-1471 has no listed developer and is somehow able to bypass the application approval process to go directly to distribution. SCP-1471 is also able to avoid removal by other program manager applications.
    .
    After SCP-1471 is installed, no icons or shortcuts are created for the application. SCP-1471 will then begin to send the individual images through text messaging every 3-6 hours. All images will contain SCP-1471-A either within the background or foreground. SCP-1471-A appears as a large humanoid figure with a canid-like skull and black hair.
    .
    During the first 24 hours following the installation of SCP-1471, the mobile device will receive images taken at locations commonly frequented by the individual. After 48 hours, the mobile device will receive images taken at locations that were recently visited by the individual. After 72 hours, the mobile device will receive images of the individual in real time with SCP-1471-A appearing within close proximity to the subject.
    .
    Individuals with >90 hours of exposure to these continuous images will begin to briefly visualize SCP-1471-A within their peripheral vision, reflective surfaces, or a combination of the two. Continued exposure to SCP-1471 after this point will cause irreversible and sustained visualizations of SCP-1471-A. Individuals at this stage have reported periodic attempts made by SCP-1471-A to visually communicate with them, but fail to understand or comprehend these actions. Currently the only known treatment to reverse SCP-1471's effect is to eliminate the individual's visual exposure to these images prior to 90 hours after installation. To date, no apparent hostile activity has been reported regarding SCP-1471-A.]]
  }
  [16]: {
    [[SCP-991-1 is a 19 cm long syringe. While the plunger is made of steel, the barrel and needle appear to be composed of previously unknown materials. When inserted into the blood vessel of a human and drawn, SCP-991-1 fills with an unknown black fluid, given the designation SCP-991-2. Once drawn from an individual (henceforth known as the donor), the plunger of the syringe cannot be pressed unless the needle of SCP-991-1 has been inserted into another human. Visual analysis of SCP-991-2 has shown it to have a significantly lower viscosity than blood, but direct analysis has proven impossible, due to the nature of SCP-991-1. Attempts to draw SCP-991-2 from a vein using a normal needle immediately after it was injected with SCP-991-1 have met with failure; apparently SCP-991-2 either disperses the instant it is injected or becomes immaterial.
    .
    When injected with SCP-991-2, the individual (henceforth known as the recipient) will instantly take on the thoughts, emotions, and memories at the forefront of the donor's mind during SCP-991-2 extraction. The further back the plunger is drawn (i.e. the more SCP-991-2 present), the more potent and permanent these ideas will be. Because it is the thoughts most prevalent in the donor's mind that determine which are transferred, some level of control can be achieved. The process is imperfect, however, as unwanted ideas usually manifest in the recipient alongside the desired ones. Whether this is an aspect of SCP-991 or a lack of focus on the part of the donor has yet to be determined.
    .
    Regardless of the cause, the "thought leak" caused by SCP-991 often results in the recipient becoming unhinged, especially if he or she receives multiple injections. They begin to possess conflicting viewpoints and ideas, and exhibit symptoms similar to those of a paranoid schizophrenic. For this reason, use of non-D-class personnel as the recipient is highly discouraged.
    .
    SCP-991 appears to actually transfer thoughts, as any idea taken from the donor no longer appears in his or her mind; transferred memories, emotions, and even opinions seem to vanish from the donor when SCP-991-1 is drawn. After repeated donations, donors often begin to exhibit symptoms consistent with Alzheimer's Disease. In some cases, this will result in the loss of a fundamental faculty of the donor, such as swallowing, breathing, or blinking. In such cases, subject is to be euthanized once all relevant data on their psychology has been taken.
    .
    Use of SCP-991 on Foundation personnel is highly discouraged, and requires the consent of both the donor and recipient, as well as the approval of two (2) class-4 personnel.
    .
    SCP-991 has proven very useful for interrogation. Cooperative D-class can be used as donors for ideas of cooperation, to be injected into the individual being interrogated. Conversely, since the information desired is often at the forefront of the individual's mind, SCP-991 can be drawn from the individual and injected into another, in order to obtain the information forcibly. It is encouraged to use cooperative D-class for this as well, however, in order to prevent "thought leak" into Foundation personnel.]]
  }
  [17]: {
    [[SCP-1540 is a humanoid organism recovered in 2001 from Provo, Utah.
    .
    Every 29-30 days, SCP-1540 undergoes a 1540-A event. The organism does not possess conscious control over the events, and unless specifically informed may not be aware of them in advance. Upon the start of 1540-A, the organism will experience severe headache, followed by muscle and bone pain. Forty minutes after the event's onset, the skin of SCP-1540 will begin to secrete large quantities of viscous white substance. The substance will solidify and expand, forming a semi-transparent cocoon around the organism. Over the next six hours, SCP-1540 will gradually dissolve, and a new body will develop from the resulting material. Once the body is fully formed, the cocoon will rupture, and the new instance of SCP-1540 will emerge.
    .
    SCP-1540 instances differ in appearance, gender, and age. None of the instances have exhibited abnormal physiology or other anomalous traits. 1540-A are not ectoentropic in nature, with the organism losing 5-8% of its mass during each event. SCP-1540 typically regains the lost mass via non-anomalous means before the next 1540-A event. The organism's health is not markedly affected by these fluctuations.
    .
    SCP-1540 instances displays separate unique identities, personalities, and full memories of their previous life. These memories are internally consistent, and the locations, individuals, and events comprising them generally exist or have occurred in the manner described by SCP-1540. However, all SCP-1540 identities appear to be highly detailed fictional constructs: no records of persons matching these identities have been found, and the individuals whom SCP-1540 identifies as friends or close relatives deny any knowledge of the organism. The information used to construct SCP-1540 identities appears to be an amalgam of abstract facts, depersonalized memories of existing individuals, and fictitious experiences original to the organism. The means by which SCP-1540 obtains this knowledge are unknown.
    .
    SCP-1540 was recovered during the investigation into assumed death of Joshua Russell, born 1985. Examination of Russell's house uncovered a collection of occult literature; numerous transcripts recorded by the subject; and a videotape, containing the recording of the subject performing an unknown ritual, and the subsequent 1540-A event. The documents indicate that the subject, along with three associates of similar ages, developed the ritual shown in the recording; the designed goal of the ritual was the transformation of the performer into a "werewolf". The subject's parents were not aware of these activities.
    .
    Analysis of the recording revealed discrepancies between the procedure performed by the subject and the version outlined in the recovered literature, including the use of cheaper materials and errors in positioning of auxiliary objects. Attempts to replicate either version of the ritual did not produce anomalous results. The individuals involved in the creation of the ritual were never found, and their current status remains unknown.]]
  }
  [18]: {
    [[SCP-1981 is a standard Betamax tape. "RONALD REGAN CUT UP WHILE TALKING"(sic) has been handwritten on the adhesive sticker in felt tip pen. Laboratory analysis indicates that SCP-1981 is made of ordinary material, and serial numbers correspond with home cassette tapes produced in September of 1980. SCP-1981 was initially encountered by a filing clerk in the Ronald Reagan Presidential Library in 1991, who upon watching it alerted the police, with the intent to find the tape's creator to press "obscenity charges". A low-level police investigation was conducted, at which point the Foundation was alerted and secured SCP-1981. Class A amnesiacs were administered before █████ could be notified. Further investigation of the library's records by Foundation personnel failed to yield any leads on SCP-1981's origin.
    .
    SCP-1981 appears to be a home video recording of former United States President Ronald Reagan delivering his "Evil Empire" speech to the National Association of Evangelicals at Sheraton Twin Towers Hotel, Orlando, FL on 3/8/1983. However, at 1 minute and 10 seconds, the speech begins to deviate heavily, eventually resembling no known speech ever made by Reagan. Beginning at approximately 5 minutes, multiple incisions, lacerations and penetration wounds can be seen being slowly inflicted, though no corresponding source of these wounds is visible. Despite suffering bodily harm that would likely incapacitate an ordinary person, Reagan will continue to deliver his speech until either his vocal cords are severed or the tape degrades to static at 22:34.
    .
    Upon rewinding SCP-1981 and initiating playback, Reagan will deliver an entirely new speech, often radically different from the ones previously observed. Topics have included torture, child molestation and ritual sacrifice. Trauma inflicted upon Reagan also appears to be divergent, with impalement, genital mutilation, and [REDACTED] having all been observed. In roughly one in seven viewings of SCP-1981, a figure clothed in black robes with a conical hood will have replaced a random member of Reagan's press detail, henceforth referred to as SCP-1981-1. The significance of the appearance of SCP-1981-1 is currently unknown.
    .
    The speeches delivered by Reagan are mostly incoherent, lacking any sort of underlying thematic structure and largely being composed of nonsensical anecdotes and parables. However, occasionally references are made to future events that Reagan could not possibly have known about or predicted, such as the September 11 terrorist attacks, the result of the 2008 Russian elections, and █████ ██████████. For this reason, rigorous time and effort has been devoted to recording the speech delivered on each playback. Attempts to replicate SCP-1981 onto a similar Betamax tape have met with failure, however, cameras used to record the television SCP-1981 is broadcasted on have succeeded in "capturing" individual playbacks. Any observations performed on SCP-1981 must be recorded on the camcorder provided, and delivered for subsequent review to Dr. B█████, project supervisor.]]
  }
  [19]: {
    [[SCP-989 is a compound of C12H22O11 (Sucrose) interlaced with a substance with the chemical formula H7Xe2O4C8. The method by which this molecule was created is currently unknown, as the current principles of chemistry disagree with its composition and structure. Research is ongoing.
    .
    SCP-989 is within an ornate silver shaker, with the logo for Marshall, Carter, and Dark engraved on the bottom, hereafter referred to as SCP-989-2. There are no visible seams in the shaker, and as such there is no way known at the moment to refill SCP-989-2, though testing at this point has shown no measurable change in weight of the object, suggesting that the substance may replenish itself. This "replenishing" effect is only observed to occur if the object is left standing for more than two (2) hours without movement. Whether this is a property of SCP-989 or SCP-989-2 is unknown at this time, but it is hypothesized that the interaction of the second compound with the materials of SCP-989-2 create this effect.
    .
    When SCP-989 is elevated and released, SCP-989 enters suspension within the air. The crystals of SCP-989 surround whoever threw SCP-989 in to the air, and remain there for precisely seven (7) minutes, eighteen (18) seconds. This has shown no adverse affect on the thrower so far, as SCP-989 will not come within two (2) millimeters of the thrower, even if they walk through the cloud of SCP-989.
    .
    If any other living being enters the cloud of SCP-989, however, SCP-989 will surround the subject, and force its way in to the mucous membranes of the subject, causing severe lacerations, and coating the area with crystalline formations akin to what is colloquially known as "rock candy". This is uniformly non-fatal however, and leaves the subject blind, deaf, with moderate difficulty breathing, and in severe pain. Attempts to remove the crystalline growths have proven unsuccessful thus far.
    .
    After exiting suspension with the air, SCP-989 will deposit on any horizontal surfaces, until thrown again, wherein it will return to being in suspension. This effect can only occur if SCP-989 is dry, as a solution of SCP-989 in water did not show any anomalous properties.]]
  }
  [20]: {
    [[SCP-981 comprises of two parts. SCP-981-1 is a steel film canister dating from the late 1920s, with signs of damage concomitant with its apparent age. It is labelled in Spanish as having been copied by the Buenos Aires Cinematographic Laboratory, with the handwritten title ‘236 - Metropolis’. Other writing on the label is too worn to read, but appears to be a name and a short note in a different handwriting. Inside the canister is SCP-981-2, a reel spooled with Kodak Panchromatic nitrate film, on which is a 16mm reduction negative of the 1927 Fritz Lang film Metropolis. The film and the canister it was found in show no unusual markings or indications that they are anything other than a mass-produced stock for distribution to cinemas in the late 1920s.
    .
    When both components of SCP-981 are placed in proximity to another audiovisual storage medium containing a feature film, the data held on the secondary medium shows alterations not in accordance with any previously known form of the film. Qualitative testing showed that any time spent within 1.93m of the canister is required for effects to show on the test media. When the film is removed from the canister neither component produces the anomaly. Tests on abstract or animated films featuring no live action actors has proved to have no effect.]]
  }
  [21]: {
    [[SCP-622 is the chemical composition [DATA EXPUNGED], also known as █-██████████████ ███████████, developed by the █████ Chemical Company under the trade name “Desert in a Can”. SCP-622 was originally marketed as a security aid for large businesses to incapacitate intruders in a similar vein to tear gas or pepper spray. According to █████ Chemical Company, SCP-622 also doubled as a cleaning agent and insecticide, but due to its hazardous nature, █████ Chemical Company was shut down in 19██ before any more products of this nature could be manufactured. As of █/██/██, there are at least ███ to ████ documented cans of “Desert in a Can” remaining, most of which are still in possession and use by the following companies: [REDACTED].
    .
    According to the directions, one layer of SCP-622 is applied to hallways during a break-in or robbery. When applied, SCP-622 becomes odorless and colorless. Upon application, all moisture in the immediate area is absorbed by SCP-622, creating an easily-cleanable salt-like crust over the applied areas, identified to be the compounds sodium chloride (NaCl), magnesium sulfate (MgSO4), and ███████ ██████████ (██2██). When SCP-622 is exposed to organic life, the immediate effects are dehydration, dried eyes, and profuse sweating, which is quickly absorbed by SCP-622. Other effects include a significant drop in blood pressure, increase in heart rate, dizziness, and chills.]]
  }
  [22]: {
    [[SCP-152 is a large, hardbound book with leather bindings. The paper inside resembles vellum and is written upon in black ink. The contents of the book consist entirely of a series of entries that describe apocalyptic events, which are not always XK-class end-of-the-world scenarios but invariably deal with the extinction of humanity. The entries are arranged in chronological order, beginning with an unexplained spontaneous failure of the sun in 6000 BC and ending with other events close to the present day. Many of the entries describe apocalypses caused or facilitated by objects that are or were in Foundation custody, or are of a paranormal nature. There are also records of human extinction caused by more "conventional" means, such as nuclear warfare or deadly viral epidemics. Each entry describes in some detail the events leading up to the calamity itself, and the aftermath until the point at which the last human on Earth dies.
    .
    It has been observed that the entries in SCP-152 change to whatever language the reader is most comfortable with, up to the point where the sentence structure can change significantly from reader to reader, or even begin using colloquialisms that only the reader would understand; only the basic meaning of the entries remains constant. If multiple people are looking at SCP-152, it will read in the personal language of whomever began reading first. If no one is directly observing SCP-152, it will display the language of whomever read it last. Rarely, words will appear in the book that do not "translate" and instead appear as horizontally arranged calligraphic characters which have not been matched to any known language.
    .
    To the best knowledge of Foundation historians, most of the information contained in SCP-152 is accurate, diverging only at the point where the apocalypse occurs. In almost all cases, the difference is that a few key decisions were apparently made differently in SCP-152's version of history, leading ultimately to humankind's annihilation.
    .
    SCP-152 resists all attempts to change or write in it. Inks, graphite, charcoal, and other marking materials do not adhere to the pages, and are easily brushed off. Lasers or other heat sources do not burn into the paper. Close inspection has revealed that foreign substances are stopped from actually coming into contact with the pages: at least five (5) micrometers of empty space are always present between the pages themselves and any foreign materials that might come into contact with them. For this reason, SCP-152 does not decay, which also means that it has proven impossible to determine SCP-152's exact age.
    .
    SCP-152 is self-updating, with newly-inked entries and new descriptions of how the last human died appearing at unpredictable intervals, always on the last page of the book; the date that a new entry appears corresponds with the date given in the entry for the death of the last member of the human species. When space becomes an issue, extra pages appear along with the text, and the spine of SCP-152 broadens accordingly. There have been ███ updates to the book since it came into Foundation custody. As with past events, SCP-152 has proven to be up-to-date on current events until a point at which a catastrophe occurs. Because recent entries frequently concern entities or groups of interest to the Foundation, including the Foundation itself, SCP-152 is to be checked regularly for any information of importance.]]
  }
  [23]: {
    [[SCP-2107 designates a soft drink brand known as "Diet Ghost™" which displays anomalous properties when imbibed. SCP-2107 has to date only been encountered packaged by the individual can. Within three to seven minutes of ingestion, subjects (classified SCP-2107-a) begin to experience paranormal activity that most often falls within the colloquial expectations of an individual being haunted by a ghost or other paranormal entity. The effect continues until an as of yet undetermined point in the breakdown of SCP-2107 within the subject's body, approximately one to three hours after ingestion. Research has confirmed that the intensity of the haunting effect (herein defined by the quantity of individual paranormal facets, the probability of physical harm, and the severity of said harm) is directly proportional to the quantity of SCP-2107 imbibed.
    .
    SCP-2107 cans are the traditional variety used for soft drinks, being uniform in design and non-anomalous in composition and behavior. The can features a light blue background with the "DIET GHOST™" logo prominently featured. The catchphrase "SCARE YOUR THIRST!" appears beneath the logo. Most instances also have a sticker on the can with the text "MADE WITH NATURAL GHOSTS!" printed on it; it is unclear if cans lacking this sticker were distributed this way or if the sticker was removed before acquisition. The cans bear no nutritional information. The liquid contents are non-anomalous in chemical composition and within normal parameters for a traditional diet soft drink.]]
  }
  [24]: {
    [[SCP-1230 is an unlabeled, green hardcover book with no apparent exceptional qualities. When SCP-1230 is opened, it displays the phrase “A hero is born” on the first page viewed, while all other pages will be blank, "resetting" once the book is closed. This has no obvious effects at first, but upon falling asleep, the reader will dream of a fantasy world where they are the protagonist of a troubled land. Dreamers are completely aware and all senses work just as well as when awake. Results vary depending on the imagination of the reader and are mostly attuned to fantasies of adventure that the reader would enjoy. In the mind of the reader, these dreams have been documented to last anywhere from 45 seconds (see Experiment 1230-3) to 200 years (see Experiment 1230-5) but in reality, the reader will usually never be asleep longer than they would normally. Upon awaking, the reader is able to remember every aspect of their dream in detail. In SCP-1230-induced dreams, there is always a character called the “Book Keeper” (SCP-1230-1) appearing as a bearded man in a green cloak who claims to be the personification of SCP-1230 himself. SCP-1230-1 has been reported to be very amicable and helpful towards dreamers. It has stated that it enjoys creating these “fantasy-scapes” and always tries to shape them in such a way that the dreamer garners the most entertainment out of it. It has expressed sorrow when the dream comes to an end and asks the dreamer to “please visit again soon”.]]
  }
  [25]: {
    [[SCP-914 is a large clockwork device weighing several tons and covering an area of eighteen square meters, consisting of screw drives, belts, pulleys, gears, springs and other clockwork. It is incredibly complex, consisting of over eight million moving parts comprised mostly of tin and copper, with some wooden and cloth items observed. Observation and probing have showed no electronic assemblies or any form of power other than the “Mainspring” under the “Selection Panel”. Two large booths 3mx2.1mx2.1m (10ftx7ftx7ft) are connected via copper tubes to the main body of SCP-914, labeled “Intake” and “Output”. Between them is a copper panel with a large knob with a small arrow attached. The words Rough, Coarse, 1:1, Fine, and Very Fine are positioned at points around the knob. Below the knob is a large “key” that winds the “mainspring”.
    .
    When an object is placed in the Intake Booth, a door slides shut, and a small bell sounds. If the knob is turned to any position and the key wound up, SCP-914 will “refine” the object in the booth. No energy is lost in the process, and the object appears to be in stasis until the Output Booth door is opened. Intense observation and testing have not shown how SCP-914 accomplishes this, and no test object has ever been observed inside SCP-914 during the “refining” process. The process takes between five and ten minutes, depending on the size of the object being refined.]]
  }
  [27]: {
    [[SCP-092 is a set of 3125 audio CDs, each labeled "The Absolute Absolute Absolute Absolute BEST of The 5th Dimension!!!!!", and marked with the names of the 31 performers who have at various times been part of the American singing group "The 5th Dimension". Each instance of SCP-092, when played in a standard CD player, will produce a distinct anomalous effect upon all individuals within hearing range. The anomalous phenomenon will last 74 minutes (the duration of a standard audio CD), during which time listeners will be unable to leave hearing range, or to shut off the CD player or otherwise interrupt its function. As well, when the anomalous phenomenon finishes, all surviving listeners will engage in synchronized vocalization of the phrase "Wow, that was real cool"; synchronized vocalization has been observed in non-anglophones, pre-verbal infants, unconscious individuals, paralyzed individuals, and individuals physically incapable of speech due to laryngeal, lingual, and/or buccal damage.
    .
    The anomalous properties of each instance of SCP-092 are thematically and conceptually linked to the number 5, dimensions, and/or the members of The 5th Dimension.]]
  }
  [28]: {
    [[SCP-583 is a Sony Color Collection 60-90 min Mini DV video tape, its case composed primarily of transparent green plastic. Details of the contents of the tape itself, as described by test subjects:
    .
    * 0'00": Nothing on the tape for the first twelve seconds.
    * 0'12": Playback of a recording of "Sesame Street Live" begins, although with no sound. A date stamp of [REDACTED] is visible.
    * 2'58": █████ starts choking and tries to get out of his costume.
    * 3'12": █████ dies from apparent asphyxiation. During the next nineteen seconds, three other characters ([REDACTED], [REDACTED], and [REDACTED]) start choking and die in the same way.
    * 3'31": Recording stops. The rest of the tape is blank.
    .
    Subjects who watch SCP-583's recording suffer from a unique perception disorder: after seeing [REDACTED] die of asphyxiation, subjects witness the similar death of every character, fictional or not, that they see on TV or in a movie, hear on radio, or read about, whether printed or in electronic format. This condition appears to be permanent, ending only with the death of the subject.]]
  }
  [29]: {
    [[SCP-584 is a highly infectious viral pathogen that, if left untreated, causes a disfiguring overgrowth of supernumerary limbs (see file photos). Structurally similar to the herpes simplex family of viruses, SCP-584 spreads via direct person-to-person contact and through contact with infected bodily fluids, and can also cross the placental barrier from an infected mother to her fetus, resulting in characteristic birth defects. SCP-584 typically lies dormant deep in the dermal tissue of those infected, largely suppressed by the immune system except for sporadic outbreaks. It is estimated that upwards of 80% of those exposed to the virus are asymptomatic carriers, making actual infection rates unknowable. (Current estimates place the highest rates of infection in Asia, particularly India and China, where the virus likely originated.) The virus appears limited to humans.
    .
    An outbreak of SCP-584 typically begins with the appearance of a small (> 2cm), painless lesion, most commonly on the extremities. Often these lesions appear similar to warts or skin tags. If not removed, the lesion will quickly grow to resemble a fully functional, though often undersized, appendage. Often the appendage will be "appropriate" to the limb on which the lesion appeared, i.e., extra toes on a foot, extra hands on an arm, etc, but severe outbreaks can trigger severely disfiguring, chaotic lesion formation elsewhere on the body, such as the head and torso. Lesions can appear singly or in groups.
    .
    Notably, SCP-584 has been shown to be able to regenerate missing limbs or digits in subjects who lost them due to accident or congenital (non-genetic) defects. These "replacement" appendages are full-sized and fully functional. It is believed that SCP-584 functions by activating regenerative biological processes that normally cease shortly after embryonic formation. However, SCP-584's effect seems restricted to external organs and appendages only.]]
  }
  [30]: {
    [[SCP-1507 is a set of 15 26 pink plastic lawn flamingos made in Coral Springs, FL. Instances of SCP-1507 have the same behavior patterns as a normal specimen of Phoeniconais ruber ruber, but do not require feeding. Instances of SCP-1507 are vulnerable to the same forces as ordinary plastic would be vulnerable to, such as heat and pressure. Testing has shown they do not possess any complex intelligence.
    .
    Instances of SCP-1507 are tolerant of human activity, and are fond of playing with staff.]]
    [[SCP-1507 is a set of 15 26 pink plastic lawn flamingos made in Coral Springs, FL. Instances of SCP-1507 have the same behavior patterns as a normal specimen of Phoeniconais ruber ruber, but do not require feeding. Instances of SCP-1507 are vulnerable to the same forces as ordinary plastic would be vulnerable to, such as heat and pressure.
    .
    Instances of SCP-1507 are universally hostile towards humans, and have been known to attack personnel who enter the enclosure by dropping down on them, using their metal stands to create scratch wounds and puncture wounds in their victim's face and eyes. SCP-1507 will frequently appear docile until it attacks, leading to several cases of severe injury among research staff.]]
  }
  [31]: {
    [[Yesterday, Researcher Boyd was playing with SCP-1507-8 during his break. During this time, SCP-1507-8 playfully attempted to take food from him. Taking this as an aggressive action, Boyd knocked SCP-1507-8 to the floor, cracking the plastic shell of the creature. After the incident, all instances of SCP-1507 have become highly aggressive towards staff members. Containment procedures have been slated for revision, and in the meantime all staff members must exercise caution when going into SCP-1507's enclosure.]]
  }
  [34]: {
    [[Organic Testing of SCP-622 to determine shelf life of chemical compound [REDACTED - O5 PERSONNEL ONLY] in an outdoor environment.
    .
    Procedure: SCP-622 will be applied to a small patch of grass on the Site 16 Testing Biosphere 07 and viewed through remote monitoring devices. Moisture measured and monitored by electronic instruments. For a control, Testing Biosphere 02 and 01 were also monitored for humidity content, averaging at 68% and 73% relative humidity, respectively.
    .
    Results: Within the first minute of exposure, the humidity of Biosphere 07 dropped to 0%, forming a brown crust along where 622 was sprayed. Within two (2) minutes of testing, all flora within Biosphere 07 had shriveled up, turning into a salt-like compound similar to SCP-622. All of the mud within Biosphere 07 turned to dry, cracked dirt. After three (3) minutes, security notified testing staff that the surrounding plant life of Site 16 was beginning to turn brown outside of Biosphere 07, despite the airtight nature of the Biosphere. Site 16 staff dispatched to surround the area and stop SCP-622 from spreading. After five (5) minutes, SCP-622 has covered over 0.017 square kilometers, spreading at an estimated rate of 0.2 kilometers an hour or roughly 3 meters per minute. Site 16 proceed to dump water on the surrounding are to stop SCP-622 from spreading. SCP-622 quickly absorbs all water and continues spreading. Site 16 command level staff immediately request to enact Protocol Grey. O5 approves. Protocol Grey enacted.
    .
    --- END LOG ---
    .
    While this does pose a possible threat leading to an eventual NK-Class "Grey Goo" end of the world scenario, Foundation staff are doing their best to contain the problem. Site 16 staff have enacted Protocol Grey to slow the rate of SCP-622 spreading and are currently looking into how SCP-622 was able to breach the Biosphere Testing Facility.
    .
    To help alleviate fears, here are a few facts that we would like you all to know.
    .
    - All of the biological SCPs at Site 16 have been secured and transferred away from the spread of SCP-622. Space will be slightly more cramped, but the situation is under control and all of the SCPs are in proper containment.
    - As of now, SCP-622 has only spread a total of less than three square kilometers, and the rate has slowed thanks to Protocol Grey. At the rate it's going, it will only be able to overtake Site 16 in 7 years. Even then, we still have plenty of time before it reaches any urban areas.
    - SCP-622 can be slowed down by water; especially fluoridated water. As long as we keep pumping over water to Site 16, it will buy us extra time until we can think of a solution.
    - We have a list of all of the known companies that are still in possession of SCP-622 and are actively seeking to contain every last canister before they can be used.
    .
    Lastly, I know some of you are shaky about Protocol Grey. It may come back to bite us, but I'd much rather worry about an XK-Class end of the world event in a few hundred years than an NK-Class "Grey Goo" end of the world event in the next few weeks. We'll deal with that then, but for now, Protocol Grey is buying us time. As long as we end Protocol Grey in the next ten years, I don't think there's anything we'll need to worry about.
    .
    I will notify everyone once SCP-622 has been contained and when Site 16 staff discover why it was able to breach containment.
    .
    Carry on,
    O5-█, ██/██/██.]]
  }
  [39]: {
    [[SCP-1599 is a smooth black ceramic disk 30 cm in diameter and 15 cm thick. Although ultrasonic and radiographic examination indicate that SCP-1599 is solid ceramic, it is the creation of an anomalously high level of technological development: in addition to several capacities which are at present only theoretically possible, SCP-1599 contains a hostile intelligence which is actively engaged in espionage. The danger posed by this intelligence is lessened, but not eliminated, by the substantial damage it experienced prior to being taken into custody by the Foundation: in particular, it does not know who it is supposed to spy on, or on whose behalf.
    .
    SCP-1599 is able to gain knowledge of any individual whose skin touches its surface. The mechanism and extent of this ability are as yet undetermined; however, SCP-1599 will use any knowledge it acquires to try to convince personnel to assist it in escaping. Direct physical contact is not advised except under testing conditions.
    .
    SCP-1599 is able to produce ultra-high-resolution life-size holograms of humans, which it can animate in real time to portray any action it desires; although the majority of these humans are entertainers and other public figures, subject has demonstrated that it is able to create holograms based on Foundation personnel whom it encounters, and that it is willing to use these holograms in attempts at blackmail and/or psychological manipulation. However, the holograms are — apparently as a result of the damage SCP-1599 experienced — flawed, in that either their skin tone is lemon-yellow, their eyes are missing, or both.
    .
    SCP-1599 is able to extend six mechanical legs and the broken stumps of three other mechanical legs; the intact legs are 22 cm long and highly articulated. Each leg is tipped with five 2-cm-long talons; these talons can grip at least strongly enough to pierce cloth and break skin. SCP-1599 has demonstrated that it is able to run at speeds of 4 meters per second (although, due to its missing legs, it cannot sustain this speed for more than 3 seconds without falling), and to perform feats of dexterity ranging from picking locks to tying and untying shoelaces to rolling cigarettes to shuffling cards. [Note: SCP-1599's offer to demonstrate its ability to load a gun has been rejected, as has its offer to demonstrate its ability to use a garotte.] When the legs are retracted, they are undetectable.
    .
    SCP-1599 is able to see and hear, despite not having any discernible mechanisms with which to do so, and to speak in thirty languages (see Appendix 1599-E-14 for list of languages). However, it has — apparently as a result of the damage it experienced — lost the ability to "subvocalize" its "thoughts", and instead provides a constant spoken commentary of its observations, conclusions, and short- and long-term intentions. SCP-1599 does not seem to be aware that it is doing this.
    .
    After 40 (forty) hours and 19 (nineteen) minutes of operation, SCP-1599 expresses the need to sleep and enters a dormant state for exactly 11 (eleven) hours and 14 (fourteen) minutes. During this time it is safe to handle the object for examination purposes, but direct physical contact should still be avoided. Upon emerging from its dormancy, SCP-1599 vocalizes an entry in its internal systems log; this entry counts the number of dormancy cycles since SCP-1599 entered Foundation custody, affirms that SCP-1599 is not worthless and that its superiors have neither abandoned it nor written it off as destroyed, and documents the status of its constant search for a broadcast signal by which it can recalibrate its damaged programming.
    .
    NOTE: Although the information gleaned from 1599's 'subvocalizations' has allowed us to thwart ███ escape attempts and ██ attempts to kill Foundation personnel, please remember that the only thing we know for sure is that its purpose is to deceive and subvert. - Director ███████]]
  }
  [40]: {
    [[SCP-2395 is a giant price tag, located at 82°08'02.1"S 16°59'05.5"W in Antarctica. Observing aerial drones have recorded SCP-2395 to have the price of "$҉ 585.98" [sic].
    .
    SCP-2395 is tied to a small rebar loop embedded in the ground by a 0.7m length of twine. SCP-2395's dimensions are 258m by 90m in length and width; a 2.5 m layer of Polyethylene covers the paper inscribed with SCP-2395's price.
    .
    SCP-2395 possesses unpredictable centrifugal and centripetal movement around the rebar loop, usually being manipulated and shifted by unknown forces in random directions and velocities. One instance has occurred where SCP-2395 maintained a constant velocity of approximately 65km/h on the date of 11/2/16, spinning clockwise for 49 seconds. Researchers note the twine that secures SCP-2395 to the rebar loop may possess anomalous tensile properties.
    .
    SCP-2395-A is a wooden shack located 0.3km east of SCP-2395. The structure is empty, save for a room in which an unknown individual, presumably a human female, prohibits access from within. The door to their room is engraved with the initials "L.C.E." This individual (designated SCP-2395-B) has responded to no verbal communication, but has occasionally been recorded conversing with other entities.]]
  }
  [41]: {
    [[SCP-035 appears to be a white porcelain comedy mask, although, at times, it will change to tragedy. In these events, all existing visual records, such as photographs, video footage, even illustrations, of SCP-035 automatically change to reflect its new appearance.
    .
    A highly corrosive and degenerative viscous liquid constantly seeps from the eye and mouth holes of SCP-035. Anything coming into contact with this substance slowly decays over a period of time, depending on the material, until it has decayed completely into a pool of the original contaminant. Glass seems to react the slowest to the effects of the item, hence the construction choice of its immediate container. Living organisms that come into contact with the substance react much the same way, with no chance of recovery. Origin of the liquid is unknown. Liquid is only visible from the front, and does not emerge or is even visible from the other side.
    .
    Subjects within 1.5 to 2 meters (5-6 feet) of SCP-035, or in visual contact with it, experience a strong urge to put it on. When SCP-035 is placed on the face of an individual, an alternate brain wave pattern from SCP-035 overlaps that of the original host, effectively snuffing it out and causing brain death to the subject. Subject then claims to be the consciousness contained within SCP-035. The bodies of "possessed" subjects decay at a highly accelerated rate, eventually becoming little more than mummified corpses. Nevertheless, SCP-035 has demonstrated the ability to remain in cognitive control of a body experiencing severe structural damage, even if the subject's body literally decays to the point where motion is not mechanically possible. No effect is found to be had when placed on the face of an animal.
    .
    Conversations with SCP-035 have proven to be informative. Researchers have learned various details about other SCP objects and history in general, as SCP-035 claims to have been at many momentous events. SCP-035 displays a highly intelligent and charismatic personality, being both amiable and flattering to all those who speak with it. SCP-035 has scored in the 99th percentile on all intelligence and aptitude tests administered to it, and appears to have a photographic memory.
    .
    However, psychological analysis has discovered SCP-035 to possess a highly manipulative nature, capable of forcing sudden and profound changes to interviewer's psychological state. SCP-035 has proven to be highly sadistic, prompting some to commit suicide and transforming others into near-mindless servants with linguistic persuasion alone. SCP-035 has stated that it has intimate knowledge of the workings of the human mind and implied that it could change anyone's views if given enough time.]]
  }
  [42]: {
    [[SCP-186 is the site of an unrecorded military engagement occurring from 7/24/1917 to 8/13/1917 between elements of the Imperial German Army and forces of the Russian provisional government as part of the larger conflict of World War I, and the continuing effects resulting from its aftermath. This conflict came to be known to its participants as the Battle of Husiatyn Woods in surviving accounts.
    .
    In July of 1917, an armed engagement between a detachment of approximately 500 German soldiers and the remnants of a Russian division scattered during the German counterattack to the Kerensky Offensive took place at the location of SCP-186. The forces met in heavily forested terrain outside the town of Husiatyn in what is currently Ternopil Oblast, Ukraine. On both sides of the conflict, combatants deployed anomalous weaponry utilizing technology that has yet to be duplicated or understood at present. This battle eventually resulted in the deaths or permanent incapacitation of all forces involved, and approximately 300 civilians in its general vicinity.
    .
    The site of SCP-186, comprising an approximately 300 km2 area, is to be closed to the public under the auspices of a habitat restoration initiative for the European bison. An automated security perimeter is to be established, monitored by staff at Remote Site-355. Security personnel must patrol SCP-186 every two weeks; any anomalous phenomena observed within the security perimeter must be documented and reported to the Research Director.
    .
    All known primary sources documenting the events of SCP-186 have been secured by the Foundation. These materials are to be stored in the Site-23 Archives. Due to the age of the materials and the potential for deterioration, all access to these documents must be approved by the Site-23 Archivist and handled per their instructions.
    .
    SCP-186-1 consists of recovered weaponry dating from the initial containment of SCP-186 in 1917. All instances of SCP-186-1 are to be secured in the munitions wing of Site-23.]]
  }
  [43]: {
    [[SCP-023 is a large, sexless shaggy canine (1.5 meters at the shoulder) with black fur. Any time an individual makes eye contact with SCP-023, either that person or a member of their immediate family will die exactly one (1) year after eye contact is broken. Research into the method of selection is incomplete due to a moratorium on experiments, but the available data suggests that having a larger immediate family lessens the chance of the individual making eye contact themselves dying, and neither a pattern nor a preference in victim types have been found. This may indicate that SCP-023's victim is designated entirely at random, but it is unknown whether this selection occurs at the beginning or at the end of the one-year time period. Attempts to terminate an individual who has made eye contact with SCP-023 and their entire immediate family before the one-year time period has ended [DATA EXPUNGED].
    .
    Autopsies of individuals killed by SCP-023's effect show that, while outwardly appearing unharmed, their remains have been 'filled in' with highly compacted ash, including but not limited to all organ systems and the circulatory system. Muscle tissue, bones, and brain tissue universally show signs of exposure to temperatures above ██°C.
    .
    If not contained in a setting that at least superficially resembles a "crossroads", SCP-023 will phase through walls to get to the nearest suitable location, incinerating all materials it passes through.]]
  }
  [44]: {
    [[SCP-058 resembles a bovine heart, with four (4) arthropod-like legs used primarily for movement, and four (4) tentacles of adjustable length, covered with razor sharp spines. It has a single sharp 'stinger' on its rear, where the hole for the superior vena cava would be in a typical organ. SCP-058's tentacles can be "whipped" to a distance of 3.2 m (10.5 ft) at speeds in excess of 320 km/h (200 mph). SCP-058 is extremely hostile and will use every opportunity afforded to it to inflict damage on its surroundings. SCP-058 has been shown to be highly resilient to trauma, and should be approached with caution even when apparently incapacitated.
    .
    SCP-058 is highly mobile and capable of rapid movement on both horizontal and vertical surfaces. It has been recorded reaching a speed of approximately 90 km/h (55 mph) in short bursts, covering distances up to 200 m (656 ft), and has the ability to accelerate from 0 to 90 km/h (55 mph) in less than two (2) seconds. It has been shown to use its tentacles for increased leverage and stability, as well as utilizing them to pull itself to other surfaces at high speeds.
    .
    SCP-058 'speaks' in a human voice, though no method of producing sound has been observed in its physiology. It speaks with vocal tone and accent of an elderly British male with a slight lisp and deep voice. SCP-058 talks constantly, regardless of conditions: even when attacking, SCP-058's voice and pace of speech are unchanged. The speech of SCP-058 lacks any detectable correlation to events, persons, or exterior locations involved with SCP-058 (see Transcript of Interview 058-04).]]
  }
  [45]: {
    [[SCP-131-A and SCP-131-B (affectionately nicknamed the "Eye Pods" by personnel) are a pair of teardrop-shaped creatures roughly 30 cm (1 ft) in height, with a single blue eye in the middle of their bodies. SCP-131-A is burnt orange in color while SCP-131-B is mustard yellow. At the base of each creature is a wheel-like protrusion which allows for locomotion, suggesting that the creatures may be biomechanical in origin. The subjects can move surprisingly fast, covering over 60 m (200 ft) in a matter of seconds. The subjects, however, lack a braking system, which has led to some rather spectacular, if not overly amusing, mishaps involving the creatures. The subjects have also shown the ability to climb sheer surfaces, and have gotten lost in the air vents on more than one occasion.
    .
    The subjects seem to have the intelligence of common house cats and are insatiably curious. Most of the time they simply roll around the facility, observing personnel at work and catching peeks at other Safe class SCPs. The subjects seem to be able to communicate with each other via an untranslatable high-pitched babbling. The subjects have never been observed to blink, even in laboratories when the subjects have been videotaped for over 18 consecutive hours.
    .
    The subjects seem to respond well to any affection given to them and will quickly bond to the giver of said affection, much in the same way a puppy bonds with a human being. They will follow anyone or anything they've made a bond with anywhere, even into normally restricted areas. Although curious, the subjects can sense danger in their general vicinity, and if the object of their bond begins to approach something they register as dangerous (e.g., Euclid or Keter class objects) they will swarm around their bonded companion's feet (or appropriate extremities) while babbling in a panicked tone, as if to warn them. Because of the daily dangers faced by Site-19 staff in dealing with Euclid and Keter class objects, it is recommended that staff avoid making attempts to bond with the subjects, as it can pose a distraction during delicate operations and experiments and may pose a danger to the subjects themselves (see Addendum 131-1). If the subjects are ignored by their bonded target long enough, they will eventually lose interest and return to their normal activities.
    .
    It should be noted that the subjects require no real care or maintenance from the site staff. They do not eat, leave droppings, or even sleep. It would seem that the only sustenance they require is visual stimulation (although this requires further study to verify).
    .
    Subjects SCP-131-A and SCP-131-B were found in a cornfield outside ████████████ in the year 19██. They were promptly transported to Site-19 via [DATA EXPUNGED] and were then downgraded to Safe class and given free reign across the site once it became clear they were not broadcasting what they saw to any hostile foreign powers.]]
  }
}
